# Generated by Django 3.1.3 on 2020-12-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201220_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='num_portions',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
