# Generated by Django 3.1.3 on 2021-02-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201228_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ManyToManyField(through='api.PlannedMeal', to='api.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='plannedmeal',
            name='weekplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weekplan'),
        ),
    ]
