# Generated by Django 3.1.3 on 2021-02-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210214_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('recipes', models.ManyToManyField(through='api.Meal', to='api.Recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='weekplan',
            name='recipes',
        ),
        migrations.DeleteModel(
            name='PlannedMeal',
        ),
        migrations.DeleteModel(
            name='WeekPlan',
        ),
        migrations.AddField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan'),
        ),
        migrations.AddField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.recipe'),
        ),
    ]
