# Generated by Django 3.1.3 on 2020-12-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0004_auto_20201220_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
