# Generated by Django 3.1.3 on 2021-02-14 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0006_auto_20210214_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekplan',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weekplan',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
